repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        description: Runs pylint on python sources
        language: system
        entry: pylint
        types: [python]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
      - id: blacken-docs

